# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DataProcessing.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x44\x61taProcessing.proto\"\x18\n\tReplyData\x12\x0b\n\x03msg\x18\x01 \x01(\x05\"\x1d\n\x0bRequestData\x12\x0e\n\x06images\x18\x01 \x01(\x0c\x32=\n\x0e\x44\x61taProcessing\x12+\n\tgetStream\x12\x0c.RequestData\x1a\n.ReplyData\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DataProcessing_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REPLYDATA']._serialized_start=24
  _globals['_REPLYDATA']._serialized_end=48
  _globals['_REQUESTDATA']._serialized_start=50
  _globals['_REQUESTDATA']._serialized_end=79
  _globals['_DATAPROCESSING']._serialized_start=81
  _globals['_DATAPROCESSING']._serialized_end=142
# @@protoc_insertion_point(module_scope)
