# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import DataProcessing_pb2 as DataProcessing__pb2


class DataProcessingStub(object):
    """responce server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getStream = channel.unary_unary(
                '/DataProcessing/getStream',
                request_serializer=DataProcessing__pb2.RequestFace.SerializeToString,
                response_deserializer=DataProcessing__pb2.Replyresult.FromString,
                )


class DataProcessingServicer(object):
    """responce server
    """

    def getStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataProcessingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getStream': grpc.unary_unary_rpc_method_handler(
                    servicer.getStream,
                    request_deserializer=DataProcessing__pb2.RequestFace.FromString,
                    response_serializer=DataProcessing__pb2.Replyresult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DataProcessing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataProcessing(object):
    """responce server
    """

    @staticmethod
    def getStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DataProcessing/getStream',
            DataProcessing__pb2.RequestFace.SerializeToString,
            DataProcessing__pb2.Replyresult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
