# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: videoinput.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10videoinput.proto\"\x16\n\x07Request\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x16\n\x05Reply\x12\r\n\x05\x64\x61tas\x18\x01 \x01(\x0c\x32\x31\n\nVideoInput\x12#\n\tgetStream\x12\x08.Request\x1a\x06.Reply\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'videoinput_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=20
  _globals['_REQUEST']._serialized_end=42
  _globals['_REPLY']._serialized_start=44
  _globals['_REPLY']._serialized_end=66
  _globals['_VIDEOINPUT']._serialized_start=68
  _globals['_VIDEOINPUT']._serialized_end=117
# @@protoc_insertion_point(module_scope)
