# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DataProcessing.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x44\x61taProcessing.proto\"\x1a\n\x0bReplyresult\x12\x0b\n\x03msg\x18\x01 \x01(\x05\";\n\x0bRequestFace\x12\x0e\n\x06images\x18\x01 \x01(\x0c\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t2;\n\x0e\x44\x61taProcessing\x12)\n\tgetStream\x12\x0c.RequestFace\x1a\x0c.Replyresult\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DataProcessing_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REPLYRESULT']._serialized_start=24
  _globals['_REPLYRESULT']._serialized_end=50
  _globals['_REQUESTFACE']._serialized_start=52
  _globals['_REQUESTFACE']._serialized_end=111
  _globals['_DATAPROCESSING']._serialized_start=113
  _globals['_DATAPROCESSING']._serialized_end=172
# @@protoc_insertion_point(module_scope)
