# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DataForwarding.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x44\x61taForwarding.proto\"\x1b\n\x0cReplyForward\x12\x0b\n\x03msg\x18\x01 \x01(\x05\"H\n\x0eRequestForward\x12\x0e\n\x06images\x18\x01 \x01(\x0c\x12\x11\n\ttrack_ids\x18\x02 \x01(\x0c\x12\x13\n\x0b\x66rame_index\x18\x03 \x01(\x05\x32?\n\x0e\x44\x61taForwarding\x12-\n\tgetStream\x12\x0f.RequestForward\x1a\r.ReplyForward\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DataForwarding_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REPLYFORWARD']._serialized_start=24
  _globals['_REPLYFORWARD']._serialized_end=51
  _globals['_REQUESTFORWARD']._serialized_start=53
  _globals['_REQUESTFORWARD']._serialized_end=125
  _globals['_DATAFORWARDING']._serialized_start=127
  _globals['_DATAFORWARDING']._serialized_end=190
# @@protoc_insertion_point(module_scope)
